all: consumer.c producer.c main.c
	gcc -o consumer consumer.c
	gcc -o producer producer.c
	gcc -o main main.c
	
clean:
	rm consumer producer main PRODUCER_BLACK.txt PRODUCER_RED.txt PRODUCER_WHITE.txt
